# Generated by Django 3.2.4 on 2021-06-10 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientAccounts',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(blank=True, max_length=6)),
                ('phno', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
