# Generated by Django 3.2.4 on 2021-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sectionNoDetails',
            fields=[
                ('serial_No', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('section_No', models.CharField(blank=True, max_length=10)),
                ('section_name', models.CharField(blank=True, max_length=28)),
                ('chapter_No', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
