# Generated by Django 3.2.4 on 2021-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_sectionnodetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccounts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
