# Generated by Django 3.2.4 on 2021-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_clientaccounts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccounts',
            name='hiredAd_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
