# Generated by Django 3.2.4 on 2021-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientaccounts_hiredad_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccounts',
            name='hiredAd_username',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
