# Generated by Django 3.2.4 on 2021-06-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clientaccounts_hiredad_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaccounts',
            old_name='hiredAd_username',
            new_name='hiredAdUsername',
        ),
    ]
