# Generated by Django 3.2.4 on 2021-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_rename_hiredad_username_clientaccounts_hiredadusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccounts',
            name='hiredAdUsername',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
