# Generated by Django 3.2.4 on 2021-06-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientaccounts_confirmedads'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccounts',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
