# Generated by Django 3.2.4 on 2021-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientaccounts_contacted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccounts',
            name='contacted',
        ),
        migrations.AddField(
            model_name='clientaccounts',
            name='contactedAds',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
