# Generated by Django 3.2.4 on 2021-06-30 10:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=30)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('noHours', models.IntegerField(blank=True, default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
            options={
            
            'managed': True,
        },
        ),
    ]
