# Generated by Django 3.2.4 on 2021-06-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={},
        ),
    ]
