# Generated by Django 3.2.4 on 2021-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
