# Generated by Django 3.2.4 on 2021-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=30)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('due_date', models.CharField(blank=True, max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=30)),
                ('service', models.TextField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=254)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('noHours', models.IntegerField(blank=True, default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
    ]
