# Generated by Django 3.2.4 on 2021-06-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_no', models.CharField(max_length=12)),
                ('enrollment_date', models.DateField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
