# Generated by Django 3.2.4 on 2021-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateaccounts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
