# Generated by Django 3.2.4 on 2021-06-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0002_alter_advocateaccounts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateaccounts',
            name='qualification',
        ),
    ]
