# Generated by Django 3.2.4 on 2021-06-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0003_remove_advocateaccounts_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateaccounts',
            name='address',
            field=models.CharField(default='Nil', max_length=255),
        ),
        migrations.AlterField(
            model_name='advocateaccounts',
            name='description',
            field=models.TextField(default='Nil', max_length=300),
        ),
    ]
