# Generated by Django 3.2.4 on 2021-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0005_remove_advocateaccounts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateaccounts',
            name='clientRequest',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='advocateaccounts',
            name='confirmedClients',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
