# Generated by Django 3.2.4 on 2021-06-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0006_auto_20210624_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateaccounts',
            name='additionalExpertises',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
